Added methods getters/setters for age and drinking age,method for drinking age
2rk/classical pull request #1
Opened 2017-03-14 08:21 UTC by cpalmerbright

2017-03-14 11:07 UTC, nigelr requested changes

2017-03-14 11:07 UTC, nigelr commented on models/human.rb
> +    return @age >= @drinking_age
you don't need to include the return here, methods by default return the last thing evaluated

2017-03-14 11:07 UTC, nigelr commented on specs/models/human_spec.rb
> +
formatting only, don't leave a line between ends

2017-03-14 11:07 UTC, nigelr commented on specs/models/human_spec.rb
> +    it 'returns true if instance of human is younger than drinking_age' do
your description is wrong here 
This is known as a copy and paste error...

2017-03-14 11:07 UTC, nigelr commented on specs/models/human_spec.rb
> +  describe '.can_drink?' do
you should only `describe '.can_drink?' do` once and group all the `it`s inside it.

2017-03-14 11:07 UTC, nigelr commented on specs/models/human_spec.rb
> +    it 'returns true if instance of human is the same age as drinking_age' do
What if `age` or `drinking_age` was not set or was set to nil

2017-03-14 11:23 UTC, cpalmerbright commented on specs/models/human_spec.rb
> +    it 'returns true if instance of human is the same age as drinking_age' do
is there a standard way to deal with these situations? 
Should I have the can_drink? method also return nil, or should I have it return false automatically, or should it return a request for the user to set those values first?

2017-03-17 12:37 UTC, nigelr requested changes

2017-03-17 12:37 UTC, nigelr commented on models/human.rb
> +    @drinking_age ||= 18
might this be a situation where having `def drinking_age` getter may be better and we default it there ensuring any other method that uses it defaults to the same value.
ps. same for `age`

2017-03-17 12:37 UTC, nigelr commented on models/human.rb
> +    @drinking_age ||= 18
pps. and you would need to test for this as well

2020-03-31 23:00 UTC, closed without merging