Ageist homework
2rk/classical pull request #4
Opened 2017-03-17 23:01 UTC by sarah398

drinking age

2017-03-17 23:57 UTC, nigelr requested changes

2017-03-17 23:57 UTC, nigelr commented on Gemfile.lock
> +  x64-mingw32
Is this something needed for Windows specifically?

2017-03-17 23:57 UTC, nigelr commented on models/human.rb
> +def to_drink
you have to_drink defined twice

2017-03-17 23:57 UTC, nigelr commented on models/human.rb
> +end
make sure `end` are aligned with the above `if`

2017-03-17 23:57 UTC, nigelr commented on models/human.rb
> +  if @age >= '18'
you are referring to `age` as a string not a number

2017-03-17 23:57 UTC, nigelr commented on models/human.rb
> +  if @age >= '18'
You did not need the `if` here

2017-03-17 23:57 UTC, nigelr commented on specs/models/human_spec.rb
> +    human.age = '34'
`age` should be a number not a string

2017-03-17 23:57 UTC, nigelr commented on models/human.rb
> +def to_drink
`to_drink` returns a boolean so it is better to name it `to_drink?`

2017-03-18 06:16 UTC, sarah398 commented on Gemfile.lock
> +  x64-mingw32
no idea...Ill try get rid of it

2017-03-18 06:38 UTC, sarah398 commented on models/human.rb
> +  if @age >= '18'
I remove 'if' and it gets annoyed about to_drink = true

2017-03-18 06:40 UTC, sarah398 commented on models/human.rb
> +def to_drink
I rename all to to_drink? and it gets annoyed with to_drink = true (unexpected = )

2023-02-21 22:16 UTC, closed without merging